apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vprofile-argo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vishyswaminathan/pragra.git
    targetRevision: HEAD
    path: pragra
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
