apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pv-claim
  labels: 
    app: vprodb
spec:
  resources:
    requests:
      storage: 3Gi
  volumeMode: Filesystem
  storageClassName: efs-sc
  accessModes:
    - ReadWriteOnce
