apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv
spec:
  capacity:
    storage: 5Gi  # EFS is scalable, so this is a placeholder ####
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany  # Allows multiple pods to access
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0f1b10060618566a2
